### ISSUE TITLE
Add shell commands

### ISSUE THREAD

**Issue by railken** [svenluijten/artisan-shortcuts#5]
Why limits the shortcuts only to artisan commands? Sometimes it can be really useful to group multiple commands (laravel and not)

### Example 1
`php artisan test`

 Result
`./vendor/bin/phpunit`

### Example 2
`php artisan update`

 Result
`git pull && php artisan migrate:update && ./vendor/bin/phpunit`

### Example 3
`php artisan force-install`

 Result
`php artisan migrate:fresh && php artisan app:install && ./vendor/bin/phpunit`

**Comment by svenluijten** [comment]
I'm not 100% on this to be honest. The use is there, but at that point I'd encourage people to wrap the commands (like `./vendor/bin/phpunit` and `git pull`) in their own artisan commands and use those. That way, everything in your application can be done "the Laravel way", instead of requiring either a certain shell, or worse, a certain OS. 

Do let me know what you think about that; I'm not convinced either way 😉

**Comment by ttomdewit** [comment]
@svenluijten I think Symfony's Process could be useful, that way they maintain the "OS stress" etc. I kind of like where @railken is going with this, but in this case I'd probably prefer Composer scripts.

**Comment by svenluijten** [comment]
@ttomdewit Yeah, I know. I just think it'd be weird for a package like this to introduce that dependency while I feel like it's a very small percentage of people who will need it. For those people, I would suggest making a command like this:

```php
class UpdateCommand extends Command
{
    protected $signature = 'update';

    public function handle()
    {
        $process = new Process(["git", "pull"]);

        // etc.
    }
}
```

**Comment by railken** [comment]
@svenluijten Isn't the entire objective of this library to create shortcuts? While it's clearly possible to create a command like you posted, it defies and go against the object of the library itself: creating shortcuts. The example used can be used against the use of the entire library, i could argue: "Why i need this library? Why i need another dependency? I could simply create a command and call artisan commands". Anyway, this is only a suggestion, if the percentage  of people who need this is indeed very small, then we can close it :)
